<template>
  <div>
    <div class="loadingio-spinner-spinner-7i8d15gghe">
      <div class="ldio-ul729j85goa">
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts"></script>

<style scoped>
@keyframes ldio-ul729j85goa {
  0% {
    opacity: 1;
  }
  100% {
    opacity: 0;
  }
}
.ldio-ul729j85goa div {
  left: 48.36px;
  top: 24.96px;
  position: absolute;
  animation: ldio-ul729j85goa linear 1s infinite;
  background: #ff0078;
  width: 7.28px;
  height: 12.48px;
  border-radius: 3.64px / 4.368px;
  transform-origin: 3.64px 27.04px;
}
.ldio-ul729j85goa div:nth-child(1) {
  transform: rotate(0deg);
  animation-delay: -0.9166666666666666s;
  background: #ff0078;
}
.ldio-ul729j85goa div:nth-child(2) {
  transform: rotate(30deg);
  animation-delay: -0.8333333333333334s;
  background: #ff0078;
}
.ldio-ul729j85goa div:nth-child(3) {
  transform: rotate(60deg);
  animation-delay: -0.75s;
  background: #ff0078;
}
.ldio-ul729j85goa div:nth-child(4) {
  transform: rotate(90deg);
  animation-delay: -0.6666666666666666s;
  background: #ff0078;
}
.ldio-ul729j85goa div:nth-child(5) {
  transform: rotate(120deg);
  animation-delay: -0.5833333333333334s;
  background: #ff0078;
}
.ldio-ul729j85goa div:nth-child(6) {
  transform: rotate(150deg);
  animation-delay: -0.5s;
  background: #ff0078;
}
.ldio-ul729j85goa div:nth-child(7) {
  transform: rotate(180deg);
  animation-delay: -0.4166666666666667s;
  background: #ff0078;
}
.ldio-ul729j85goa div:nth-child(8) {
  transform: rotate(210deg);
  animation-delay: -0.3333333333333333s;
  background: #ff0078;
}
.ldio-ul729j85goa div:nth-child(9) {
  transform: rotate(240deg);
  animation-delay: -0.25s;
  background: #ff0078;
}
.ldio-ul729j85goa div:nth-child(10) {
  transform: rotate(270deg);
  animation-delay: -0.16666666666666666s;
  background: #ff0078;
}
.ldio-ul729j85goa div:nth-child(11) {
  transform: rotate(300deg);
  animation-delay: -0.08333333333333333s;
  background: #ff0078;
}
.ldio-ul729j85goa div:nth-child(12) {
  transform: rotate(330deg);
  animation-delay: 0s;
  background: #ff0078;
}
.loadingio-spinner-spinner-7i8d15gghe {
  width: 104px;
  height: 104px;
  display: inline-block;
  overflow: hidden;
  background: inherit;
}
.ldio-ul729j85goa {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-ul729j85goa div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>
